version: 0.2

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - ls -a
      - unzip terraform_0.10.3_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.10.3_linux_amd64.zip
      - apt-get update
      - ls -a